language: node_js
node_js:
- node
- '6'
- '4'
deploy:
  provider: npm
  email: marcus@stade.se
  api_key:
    secure: ztmhu+UTP+kF0QJYDGNMzdToqsoDgRhyvY8oK1+J32Z2uVJis0hjDAVVIJ8W8vSbsYLAYsgqj22vpidMOycfNAjhLVKyY/Jq5qqzYpJLJFKm2b2SM1BFXmkvyFAnYvlnOfxBZcDl5tKaPVU3AOb6FnLXL/RRreHk7H/eRKra3VX3QRPlCnm/CZi7ukYb3jA+27nu755vGlGKC8lpjYsYG2FPrU0XAFBW7GuQpjPut3vsqIaNduyn3m40cbbyxsZCJ2qw4d1AJx/V74TCzYt1oPWRtC7i8Fxi0Cs99MixJp5kAEfI+gDOc3L4mTgLlI/J7DR85wLHpZ6KZaVID7cCtNTndXtb5I8I5MEW+MP09nE0pa4qG9OWtZ2hzORPaENLE8GnXW1NPSX11MrUzUycLSqv0fTn7z94x2iTY4VvnwVVghokI/hOJpXJ/Y9e4JDpZUETLj9g3UTR41/AwSPfvXOy8w4MGLLwbenlitNaTu8fEITKrOEIzKiC9xZiz6Q783afihKUVK2LWJictNxsAPdz/a1I4hl9dFSgCltOvwLajJnCQBP9cKk8YO6mttWt4CbxxtpceBhGcZrr9WirOzWboUBbLPSMGlKUks6f7t98PxJNpoGnHIIfm7wqggUN+Ma1sG3tFvTMAs3jcGAgT9nTFseFMoXvrMvd2brPGW4=
  skip_cleanup: true
  on:
    tags: true
    repo: zambezi/ez-build
    all_branches: true
